# This workflow will install Python dependencies from a conda YAML and run tests with pytest

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('cpu_env.yaml') }}
    - uses: goanpeca/setup-miniconda@1.x
      with:
        conda-version: 4.8.3
        activate-environment: mobilesign-cpu
        python-version: 3.7
        channel-priority: strict
        environment-file: cpu_env.yaml
        use-only-tar-bz2: true

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest
