# This workflow will install Python dependencies from a conda YAML and run tests with pytest

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: mobilesign_cpu
        environment-file: cpu_env.yaml
        python-version: 3.7
#         condarc-file: etc/example-condarc.yml
        auto-activate-base: false

    - name: Test with pytest
      run: |
        pytest
