# This workflow will install Python dependencies from a conda YAML, lint with isort, black, and flake8, and run pytest

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - uses: goanpeca/setup-miniconda@v1
#       with:
#         activate-environment: anaconda-client-env
#         environment-file: etc/example-environment.yml
#         python-version: 3.5
#         condarc-file: etc/example-condarc.yml
#         auto-activate-base: false

    - name: Python style check
      uses: bulv1ne/python-style-check@v0.3
#     - name: Test with pytest
#       run: |
#         pytest
